/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ttProject_test_jni_HelloJni */

#ifndef _Included_com_ttProject_test_jni_HelloJni
#define _Included_com_ttProject_test_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ttProject_test_jni_HelloJni
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ttProject_test_jni_HelloJni_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
